Portfolio with Flex-Cards
ridaarif98/MyPortfolio pull request #2
Opened 2021-06-03 14:02 UTC by ridaarif98

In this Portfolio,
I add a grid in section
Inside grid flex-box created
Add Images to flex box
Integrate linters

2021-06-04 22:27 UTC, Dipeshtwis requested changes
Hi @Ismailco , 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Good use of Grid and Flexbox.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- For now, your text is overflowing, Below is the screenshot

![Screenshot (1372)](https://user-images.githubusercontent.com/22434660/120868599-0265ab00-c5b2-11eb-8792-6b33fa0dfdea.png)

**_Check the comments under the below_**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-04 22:27 UTC, Dipeshtwis commented on Index.html
> +          <img src="C:/git/MyPortfolio/images/Portfolio.svg" alt="MyWork">
- [ ] The image is not showing in your design.

2021-06-04 22:27 UTC, Dipeshtwis commented on Index.html
> +        </div>
- [ ] The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li`.

2021-06-04 22:27 UTC, Dipeshtwis commented on Index.html
> +    </div>
- [ ] The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`.

2021-06-05 10:22 UTC, henatan99 commented on Index.html
> +          <img src="C:/git/MyPortfolio/images/FourthPortfolio.svg" alt="MyWork">
- [ ] You images are not displaying. Please use relative path for image `src`. You can make it like `src="./images/FourthPortfolio.svg"`. Kindly make the sma changes for similar image paths too.

2021-06-05 10:22 UTC, henatan99 commented on Index.html
> +          <img src="C:/git/MyPortfolio/images/Portfolio.svg" alt="MyWork">
- [ ] This issue is not addressed! See the inline comment for this below the new review summary! :pray:

2021-06-05 10:23 UTC, henatan99 commented on Index.html
> +        </div>
This issue is addressed. Nice work! :clap:

2021-06-05 10:24 UTC, henatan99 commented on Index.html
> +    </div>
This issue is addressed. Nice work! :clap:

2021-06-05 10:43 UTC, henatan99 requested changes
Hi Rida, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 10:43 UTC, henatan99 commented on Index.html
> +      <div class="grid-item">
- [ ] The `grid-item` elements have some design issues: alignment, spacing, and typography as already pointed out by the previous reviewer. For reference see the attached screenshot images and compare your clone with the original design. 
![Screenshot (4)](https://user-images.githubusercontent.com/64894927/120888762-d292c380-c602-11eb-816c-9524185d2ff0.png)  
![Screenshot (5)](https://user-images.githubusercontent.com/64894927/120888768-d9213b00-c602-11eb-89f2-02e243135186.png)
- [ ] OPTIONAL: Semantically, the `grid-item` elements should better be `li` elements and wrapped altogether in a `ul` tag.

2021-06-05 11:06 UTC, DeliceLydia approved these changes
# Status: Approved🎉 🎉 

Hi @ridaarif98, 

Your project is complete! I can see the hard work from your project you nailed it! There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Keep Aiming High!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 11:06 UTC, DeliceLydia commented on Index.html
> +      <div class="grid-item">
Well addressed this✔️

2021-06-05 11:08 UTC, merged